M48
; DRILL file {KiCad 7.0.6} date Tue Aug 29 11:28:12 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-29T11:28:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X107.27Y-81.325
X107.27Y-86.175
T2
X110.3Y-81.025
X110.3Y-86.475
T0
M30
